language: cpp

os:
  - linux

sudo: required
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libdc1394-22-dev
      - libgl1-mesa-dev

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.14.0-bionic -y
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq qt514base qt514declarative qt514quickcontrols
script:
    - source /opt/qt514/bin/qt514-env.sh
    - qmake -r
    - make
    - export LD_LIBRARY_PATH=$(pwd)/build
    - make check
