os: unstable
image: Visual Studio 2017

platform:
  - x64
  
install:
  - SET QTDIR=C:\Qt\5.13.2\mingw73_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw730_32
build_script:
  - qmake -r qmlgantt.pro
  - mingw32-make
