os: unstable
image: Visual Studio 2017

platform:
  - x64
  
install:
  - SET QTDIR=C:\Qt\5.13.2\mingw73_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\Tools\mingw73_64\bin
build_script:
  - qmake -r qmlgantt.pro
  - mingw32-make
